# Fetching the Data

In [ ]:
import pandas as pd

df = pd.read_csv('data/bbc-news-summary.csv')
df.head()

,File_path,Articles,Summaries
0,politics,Budget to set scene for election..Gordon Brown...,- Increase in the stamp duty threshold from £6...
1,politics,Army chiefs in regiments decision..Military ch...,"""They are very much not for the good and will ..."
2,politics,Howard denies split over ID cards..Michael How...,Michael Howard has denied his shadow cabinet w...
3,politics,Observers to monitor UK election..Ministers wi...,The report said individual registration should...
4,politics,Kilroy names election seat target..Ex-chat sho...,"UKIP's leader, Roger Knapman, has said he is g..."

# Cleaning the data

In [2]:
before_preprocess = df['Articles'][0]
before_preprocess

'Budget to set scene for election..Gordon Brown will seek to put the economy at the centre of Labour\'s bid for a third term in power when he delivers his ninth Budget at 1230 GMT. He is expected to stress the importance of continued economic stability, with low unemployment and interest rates. The chancellor is expected to freeze petrol duty and raise the stamp duty threshold from £60,000. But the Conservatives and Lib Dems insist voters face higher taxes and more means-testing under Labour...Treasury officials have said there will not be a pre-election giveaway, but Mr Brown is thought to have about £2bn to spare...- Increase in the stamp duty threshold from £60,000. - A freeze on petrol duty. - An extension of tax credit scheme for poorer families. - Possible help for pensioners The stamp duty threshold rise is intended to help first time buyers - a likely theme of all three of the main parties\' general election manifestos. Ten years ago, buyers had a much greater chance of avoiding stamp duty, with close to half a million properties, in England and Wales alone, selling for less than £60,000. Since then, average UK property prices have more than doubled while the starting threshold for stamp duty has not increased. Tax credits As a result, the number of properties incurring stamp duty has rocketed as has the government\'s tax take. The Liberal Democrats unveiled their own proposals to raise the stamp duty threshold to £150,000 in February...The Tories are also thought likely to propose increased thresholds, with shadow chancellor Oliver Letwin branding stamp duty a "classic Labour stealth tax". The Tories say whatever the chancellor gives away will be clawed back in higher taxes if Labour is returned to power. Shadow Treasury chief secretary George Osborne said: "Everyone who looks at the British economy at the moment says there has been a sharp deterioration in the public finances, that there is a black hole," he said. "If Labour is elected there will be a very substantial tax increase in the Budget after the election, of the order of around £10bn."..But Mr Brown\'s former advisor Ed Balls, now a parliamentary hopeful, said an examination of Tory plans for the economy showed there would be a £35bn difference in investment by the end of the next parliament between the two main parties. He added: "I don\'t accept there is any need for any changes to the plans we have set out to meet our spending commitments."..For the Lib Dems David Laws said: "The chancellor will no doubt tell us today how wonderfully the economy is doing," he said. "But a lot of that is built on an increase in personal and consumer debt over the last few years - that makes the economy quite vulnerable potentially if interest rates ever do have to go up in a significant way." SNP leader Alex Salmond said his party would introduce a £2,000 grant for first time buyers, reduce corporation tax and introduce a citizens pension free from means testing. Plaid Cymru\'s economics spokesman Adam Price said he wanted help to get people on the housing ladder and an increase in the minimum wage to £5.60 an hour.'

In [3]:
df['Articles'][0]

'Budget to set scene for election..Gordon Brown will seek to put the economy at the centre of Labour\'s bid for a third term in power when he delivers his ninth Budget at 1230 GMT. He is expected to stress the importance of continued economic stability, with low unemployment and interest rates. The chancellor is expected to freeze petrol duty and raise the stamp duty threshold from £60,000. But the Conservatives and Lib Dems insist voters face higher taxes and more means-testing under Labour...Treasury officials have said there will not be a pre-election giveaway, but Mr Brown is thought to have about £2bn to spare...- Increase in the stamp duty threshold from £60,000. - A freeze on petrol duty. - An extension of tax credit scheme for poorer families. - Possible help for pensioners The stamp duty threshold rise is intended to help first time buyers - a likely theme of all three of the main parties\' general election manifestos. Ten years ago, buyers had a much greater chance of avoiding stamp duty, with close to half a million properties, in England and Wales alone, selling for less than £60,000. Since then, average UK property prices have more than doubled while the starting threshold for stamp duty has not increased. Tax credits As a result, the number of properties incurring stamp duty has rocketed as has the government\'s tax take. The Liberal Democrats unveiled their own proposals to raise the stamp duty threshold to £150,000 in February...The Tories are also thought likely to propose increased thresholds, with shadow chancellor Oliver Letwin branding stamp duty a "classic Labour stealth tax". The Tories say whatever the chancellor gives away will be clawed back in higher taxes if Labour is returned to power. Shadow Treasury chief secretary George Osborne said: "Everyone who looks at the British economy at the moment says there has been a sharp deterioration in the public finances, that there is a black hole," he said. "If Labour is elected there will be a very substantial tax increase in the Budget after the election, of the order of around £10bn."..But Mr Brown\'s former advisor Ed Balls, now a parliamentary hopeful, said an examination of Tory plans for the economy showed there would be a £35bn difference in investment by the end of the next parliament between the two main parties. He added: "I don\'t accept there is any need for any changes to the plans we have set out to meet our spending commitments."..For the Lib Dems David Laws said: "The chancellor will no doubt tell us today how wonderfully the economy is doing," he said. "But a lot of that is built on an increase in personal and consumer debt over the last few years - that makes the economy quite vulnerable potentially if interest rates ever do have to go up in a significant way." SNP leader Alex Salmond said his party would introduce a £2,000 grant for first time buyers, reduce corporation tax and introduce a citizens pension free from means testing. Plaid Cymru\'s economics spokesman Adam Price said he wanted help to get people on the housing ladder and an increase in the minimum wage to £5.60 an hour.'

In [4]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

<h2> Word Lowering </h2>

In [5]:
df['Articles'] = df['Articles'].str.lower()
df['Summaries'] = df['Summaries'].str.lower()

<h2> Tokenization </h2>

In [6]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\omara\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [7]:
from nltk.tokenize import word_tokenize
df['Articles'] = [word_tokenize(x) for x in df['Articles']]

<h2>Part of Speech (POS)</h2>

In [8]:
from nltk import pos_tag
from nltk.tag import DefaultTagger

# nltk.download('averaged_perceptron_tagger_eng')

df["ArticlesPOS"] = [pos_tag(x) for x in df['Articles']]
df.head()

,File_path,Articles,Summaries,ArticlesPOS
0,politics,"[budget, to, set, scene, for, election, .., go...",- increase in the stamp duty threshold from £6...,"[(budget, NN), (to, TO), (set, VB), (scene, NN..."
1,politics,"[army, chiefs, in, regiments, decision, .., mi...","""they are very much not for the good and will ...","[(army, NN), (chiefs, NNS), (in, IN), (regimen..."
2,politics,"[howard, denies, split, over, id, cards, .., m...",michael howard has denied his shadow cabinet w...,"[(howard, NN), (denies, VBZ), (split, VBN), (o..."
3,politics,"[observers, to, monitor, uk, election, .., min...",the report said individual registration should...,"[(observers, NNS), (to, TO), (monitor, VB), (u..."
4,politics,"[kilroy, names, election, seat, target, .., ex...","ukip's leader, roger knapman, has said he is g...","[(kilroy, NN), (names, NNS), (election, NN), (..."

<h2> Stopword removal

In [9]:
# from nltk.corpus import stopwords

# nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\omara\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
mystopwords= stopwords.words("english")

df['Articles'] = [[word for word in tokens if word not in mystopwords] for tokens in df['Articles']]
df['Articles'][0]

['budget',
 'set',
 'scene',
 'election',
 '..',
 'gordon',
 'brown',
 'seek',
 'put',
 'economy',
 'centre',
 'labour',
 "'s",
 'bid',
 'third',
 'term',
 'power',
 'delivers',
 'ninth',
 'budget',
 '1230',
 'gmt',
 '.',
 'expected',
 'stress',
 'importance',
 'continued',
 'economic',
 'stability',
 ',',
 'low',
 'unemployment',
 'interest',
 'rates',
 '.',
 'chancellor',
 'expected',
 'freeze',
 'petrol',
 'duty',
 'raise',
 'stamp',
 'duty',
 'threshold',
 '£60,000',
 '.',
 'conservatives',
 'lib',
 'dems',
 'insist',
 'voters',
 'face',
 'higher',
 'taxes',
 'means-testing',
 'labour',
 '...',
 'treasury',
 'officials',
 'said',
 'pre-election',
 'giveaway',
 ',',
 'mr',
 'brown',
 'thought',
 '£2bn',
 'spare',
 '...',
 '-',
 'increase',
 'stamp',
 'duty',
 'threshold',
 '£60,000',
 '.',
 '-',
 'freeze',
 'petrol',
 'duty',
 '.',
 '-',
 'extension',
 'tax',
 'credit',
 'scheme',
 'poorer',
 'families',
 '.',
 '-',
 'possible',
 'help',
 'pensioners',
 'stamp',
 'duty',
 'threshold',
 'rise',
 'intended',
 'help',
 'first',
 'time',
 'buyers',
 '-',
 'likely',
 'theme',
 'three',
 'main',
 'parties',
 "'",
 'general',
 'election',
 'manifestos',
 '.',
 'ten',
 'years',
 'ago',
 ',',
 'buyers',
 'much',
 'greater',
 'chance',
 'avoiding',
 'stamp',
 'duty',
 ',',
 'close',
 'half',
 'million',
 'properties',
 ',',
 'england',
 'wales',
 'alone',
 ',',
 'selling',
 'less',
 '£60,000',
 '.',
 'since',
 ',',
 'average',
 'uk',
 'property',
 'prices',
 'doubled',
 'starting',
 'threshold',
 'stamp',
 'duty',
 'increased',
 '.',
 'tax',
 'credits',
 'result',
 ',',
 'number',
 'properties',
 'incurring',
 'stamp',
 'duty',
 'rocketed',
 'government',
 "'s",
 'tax',
 'take',
 '.',
 'liberal',
 'democrats',
 'unveiled',
 'proposals',
 'raise',
 'stamp',
 'duty',
 'threshold',
 '£150,000',
 'february',
 '...',
 'tories',
 'also',
 'thought',
 'likely',
 'propose',
 'increased',
 'thresholds',
 ',',
 'shadow',
 'chancellor',
 'oliver',
 'letwin',
 'branding',
 'stamp',
 'duty',
 '``',
 'classic',
 'labour',
 'stealth',
 'tax',
 "''",
 '.',
 'tories',
 'say',
 'whatever',
 'chancellor',
 'gives',
 'away',
 'clawed',
 'back',
 'higher',
 'taxes',
 'labour',
 'returned',
 'power',
 '.',
 'shadow',
 'treasury',
 'chief',
 'secretary',
 'george',
 'osborne',
 'said',
 ':',
 '``',
 'everyone',
 'looks',
 'british',
 'economy',
 'moment',
 'says',
 'sharp',
 'deterioration',
 'public',
 'finances',
 ',',
 'black',
 'hole',
 ',',
 "''",
 'said',
 '.',
 '``',
 'labour',
 'elected',
 'substantial',
 'tax',
 'increase',
 'budget',
 'election',
 ',',
 'order',
 'around',
 '£10bn',
 '.',
 '``',
 '..',
 'mr',
 'brown',
 "'s",
 'former',
 'advisor',
 'ed',
 'balls',
 ',',
 'parliamentary',
 'hopeful',
 ',',
 'said',
 'examination',
 'tory',
 'plans',
 'economy',
 'showed',
 'would',
 '£35bn',
 'difference',
 'investment',
 'end',
 'next',
 'parliament',
 'two',
 'main',
 'parties',
 '.',
 'added',
 ':',
 '``',
 "n't",
 'accept',
 'need',
 'changes',
 'plans',
 'set',
 'meet',
 'spending',
 'commitments',
 '.',
 '``',
 '..',
 'lib',
 'dems',
 'david',
 'laws',
 'said',
 ':',
 '``',
 'chancellor',
 'doubt',
 'tell',
 'us',
 'today',
 'wonderfully',
 'economy',
 ',',
 "''",
 'said',
 '.',
 '``',
 'lot',
 'built',
 'increase',
 'personal',
 'consumer',
 'debt',
 'last',
 'years',
 '-',
 'makes',
 'economy',
 'quite',
 'vulnerable',
 'potentially',
 'interest',
 'rates',
 'ever',
 'go',
 'significant',
 'way',
 '.',
 "''",
 'snp',
 'leader',
 'alex',
 'salmond',
 'said',
 'party',
 'would',
 'introduce',
 '£2,000',
 'grant',
 'first',
 'time',
 'buyers',
 ',',
 'reduce',
 'corporation',
 'tax',
 'introduce',
 'citizens',
 'pension',
 'free',
 'means',
 'testing',
 '.',
 'plaid',
 'cymru',
 "'s",
 'economics',
 'spokesman',
 'adam',
 'price',
 'said',
 'wanted',
 'help',
 'get',
 'people',
 'housing',
 'ladder',
 'increase',
 'minimum',
 'wage',
 '£5.60',
 'hour',
 '.']

<h2> Lemmatization </h2>

In [11]:
from nltk.stem import WordNetLemmatizer

wnl = WordNetLemmatizer()

lemmatized_articles = []
for tokens in df["Articles"]:
    lemmatized_tokens = []
    for word in tokens:
        word = wnl.lemmatize(word, "n")
        word = wnl.lemmatize(word, "v")
        word = wnl.lemmatize(word, "a")
        lemmatized_tokens.append(word)
    lemmatized_articles.append(lemmatized_tokens)

df['Articles'] = lemmatized_articles
df['Articles'] = [" ".join(x) for x in df['Articles']]
df['Articles'][0]

"budget set scene election .. gordon brown seek put economy centre labour 's bid third term power deliver ninth budget 1230 gmt . expect stress importance continue economic stability , low unemployment interest rate . chancellor expect freeze petrol duty raise stamp duty threshold £60,000 . conservative lib dems insist voter face high tax means-testing labour ... treasury official say pre-election giveaway , mr brown think £2bn spare ... - increase stamp duty threshold £60,000 . - freeze petrol duty . - extension tax credit scheme poor family . - possible help pensioner stamp duty threshold rise intend help first time buyer - likely theme three main party ' general election manifesto . ten year ago , buyer much great chance avoid stamp duty , close half million property , england wale alone , sell less £60,000 . since , average uk property price double start threshold stamp duty increase . tax credit result , number property incur stamp duty rocket government 's tax take . liberal democrat unveil proposal raise stamp duty threshold £150,000 february ... tory also think likely propose increase threshold , shadow chancellor oliver letwin brand stamp duty `` classic labour stealth tax '' . tory say whatever chancellor give away claw back high tax labour return power . shadow treasury chief secretary george osborne say : `` everyone look british economy moment say sharp deterioration public finance , black hole , '' say . `` labour elect substantial tax increase budget election , order around £10bn . `` .. mr brown 's former advisor ed ball , parliamentary hopeful , say examination tory plan economy show would £35bn difference investment end next parliament two main party . add : `` n't accept need change plan set meet spend commitment . `` .. lib dems david law say : `` chancellor doubt tell u today wonderfully economy , '' say . `` lot build increase personal consumer debt last year - make economy quite vulnerable potentially interest rate ever go significant way . '' snp leader alex salmond say party would introduce £2,000 grant first time buyer , reduce corporation tax introduce citizen pension free mean test . plaid cymru 's economics spokesman adam price say want help get people house ladder increase minimum wage £5.60 hour ."

In [12]:
after_preprocess = df['Articles'][0]
print(before_preprocess)
print(after_preprocess)

Budget to set scene for election..Gordon Brown will seek to put the economy at the centre of Labour's bid for a third term in power when he delivers his ninth Budget at 1230 GMT. He is expected to stress the importance of continued economic stability, with low unemployment and interest rates. The chancellor is expected to freeze petrol duty and raise the stamp duty threshold from £60,000. But the Conservatives and Lib Dems insist voters face higher taxes and more means-testing under Labour...Treasury officials have said there will not be a pre-election giveaway, but Mr Brown is thought to have about £2bn to spare...- Increase in the stamp duty threshold from £60,000. - A freeze on petrol duty. - An extension of tax credit scheme for poorer families. - Possible help for pensioners The stamp duty threshold rise is intended to help first time buyers - a likely theme of all three of the main parties' general election manifestos. Ten years ago, buyers had a much greater chance of avoiding stamp duty, with close to half a million properties, in England and Wales alone, selling for less than £60,000. Since then, average UK property prices have more than doubled while the starting threshold for stamp duty has not increased. Tax credits As a result, the number of properties incurring stamp duty has rocketed as has the government's tax take. The Liberal Democrats unveiled their own proposals to raise the stamp duty threshold to £150,000 in February...The Tories are also thought likely to propose increased thresholds, with shadow chancellor Oliver Letwin branding stamp duty a "classic Labour stealth tax". The Tories say whatever the chancellor gives away will be clawed back in higher taxes if Labour is returned to power. Shadow Treasury chief secretary George Osborne said: "Everyone who looks at the British economy at the moment says there has been a sharp deterioration in the public finances, that there is a black hole," he said. "If Labour is elected there will be a very substantial tax increase in the Budget after the election, of the order of around £10bn."..But Mr Brown's former advisor Ed Balls, now a parliamentary hopeful, said an examination of Tory plans for the economy showed there would be a £35bn difference in investment by the end of the next parliament between the two main parties. He added: "I don't accept there is any need for any changes to the plans we have set out to meet our spending commitments."..For the Lib Dems David Laws said: "The chancellor will no doubt tell us today how wonderfully the economy is doing," he said. "But a lot of that is built on an increase in personal and consumer debt over the last few years - that makes the economy quite vulnerable potentially if interest rates ever do have to go up in a significant way." SNP leader Alex Salmond said his party would introduce a £2,000 grant for first time buyers, reduce corporation tax and introduce a citizens pension free from means testing. Plaid Cymru's economics spokesman Adam Price said he wanted help to get people on the housing ladder and an increase in the minimum wage to £5.60 an hour.
budget set scene election .. gordon brown seek put economy centre labour 's bid third term power deliver ninth budget 1230 gmt . expect stress importance continue economic stability , low unemployment interest rate . chancellor expect freeze petrol duty raise stamp duty threshold £60,000 . conservative lib dems insist voter face high tax means-testing labour ... treasury official say pre-election giveaway , mr brown think £2bn spare ... - increase stamp duty threshold £60,000 . - freeze petrol duty . - extension tax credit scheme poor family . - possible help pensioner stamp duty threshold rise intend help first time buyer - likely theme three main party ' general election manifesto . ten year ago , buyer much great chance avoid stamp duty , close half million property , england wale alone , sell less £60,000 . since , average uk property price double start threshold stamp duty increase . tax credit result , number property incur stamp duty rocket government 's tax take . liberal democrat unveil proposal raise stamp duty threshold £150,000 february ... tory also think likely propose increase threshold , shadow chancellor oliver letwin brand stamp duty `` classic labour stealth tax '' . tory say whatever chancellor give away claw back high tax labour return power . shadow treasury chief secretary george osborne say : `` everyone look british economy moment say sharp deterioration public finance , black hole , '' say . `` labour elect substantial tax increase budget election , order around £10bn . `` .. mr brown 's former advisor ed ball , parliamentary hopeful , say examination tory plan economy show would £35bn difference investment end next parliament two main party . add : `` n't accept need change plan set meet spend commitment . `` .. lib dems david law say : `` chancellor doubt tell u today wonderfully economy , '' say . `` lot build increase personal consumer debt last year - make economy quite vulnerable potentially interest rate ever go significant way . '' snp leader alex salmond say party would introduce £2,000 grant first time buyer , reduce corporation tax introduce citizen pension free mean test . plaid cymru 's economics spokesman adam price say want help get people house ladder increase minimum wage £5.60 hour .

In [14]:
data = []

for i, text in enumerate(df['Articles']):
    data.append({"TextID": i, "Text": text})

data

[{'TextID': 0,
  'Text': "budget set scene election .. gordon brown seek put economy centre labour 's bid third term power deliver ninth budget 1230 gmt . expect stress importance continue economic stability , low unemployment interest rate . chancellor expect freeze petrol duty raise stamp duty threshold £60,000 . conservative lib dems insist voter face high tax means-testing labour ... treasury official say pre-election giveaway , mr brown think £2bn spare ... - increase stamp duty threshold £60,000 . - freeze petrol duty . - extension tax credit scheme poor family . - possible help pensioner stamp duty threshold rise intend help first time buyer - likely theme three main party ' general election manifesto . ten year ago , buyer much great chance avoid stamp duty , close half million property , england wale alone , sell less £60,000 . since , average uk property price double start threshold stamp duty increase . tax credit result , number property incur stamp duty rocket government 's tax take . liberal democrat unveil proposal raise stamp duty threshold £150,000 february ... tory also think likely propose increase threshold , shadow chancellor oliver letwin brand stamp duty `` classic labour stealth tax '' . tory say whatever chancellor give away claw back high tax labour return power . shadow treasury chief secretary george osborne say : `` everyone look british economy moment say sharp deterioration public finance , black hole , '' say . `` labour elect substantial tax increase budget election , order around £10bn . `` .. mr brown 's former advisor ed ball , parliamentary hopeful , say examination tory plan economy show would £35bn difference investment end next parliament two main party . add : `` n't accept need change plan set meet spend commitment . `` .. lib dems david law say : `` chancellor doubt tell u today wonderfully economy , '' say . `` lot build increase personal consumer debt last year - make economy quite vulnerable potentially interest rate ever go significant way . '' snp leader alex salmond say party would introduce £2,000 grant first time buyer , reduce corporation tax introduce citizen pension free mean test . plaid cymru 's economics spokesman adam price say want help get people house ladder increase minimum wage £5.60 hour ."},
 {'TextID': 1,
  'Text': "army chief regiment decision .. military chief expect meet make final decision future scotland 's army regiment ... committee army board , make senior defence figure , discus plan restructure regiment monday . proposal include cut scotland 's six single-battalion regiment five merge super regiment . plan face stiff opposition campaigner politician alike . committee 's decision must ratify defence secretary geoff hoon prime minister tony blair . expect make public next week . minister announce reorganisation army draw question mark future black watch , king scottish borderer , royal scot , royal highland fusilier argyll sutherland highland . october , council scottish colonel propose merger royal scot king 's scottish borderer single battalion ... vision , would one five new super regiment . proposal either merge amalgamate six regiment super regiment spark political outcry , labour backbencher opposition politician oppose plan . felt time insensitive black watch frontline iraq , suffer casualty . save scottish regiment campaigner anger threaten stand labour next general election ... speak ahead expect army board meet , spokesman say : `` government army board spend past four month attempt trick serve soldier public think plan change scottish regiment good army serve soldier . `` much good destroy scotland 's regiment mould single super regiment lead severe recruitment problem , loss local connection regiment loss scotland important part heritage , importantly , future - regiment envy army around world . '' alternative blueprint put forward labour mp eric joyce , propose go ahead merger preserve regiment . brief time , speculation prime minister might consider plan , seem unlikely . speak scotland last week , mr blair say aim preserve tradition introduce effective structure hint super regiment likely . say : `` n't want get rid history tradition regiment local connection - far , want make sure transfer people easily across regiment deploy flexibly . '' prime minister say hop campaigner ' concern would take account need effective change paramount ."},
 {'TextID': 2,
  'Text': "howard deny split id card .. michael howard deny shadow cabinet split decision back controversial labour plan introduce id card ... tory leader say front bench team reach `` collective view '' hold `` good discussion '' , admit `` easy issue '' . decide support plan police say would help fight terror , crime illegal immigration . lib dems pledge oppose bill debate next monday ... tory source say senior party figure argue vociferously id card scheme . among report serious reservation strategy senior shadow cabinet member david davis , oliver letwin tim yeo . mr howard deny mr yeo , transport environment spokesman , say plan `` stink '' . also say confident shadow home secretary mr davis would `` set position clearly '' stand debate matter next week . mr howard say police say id card could `` help foil terror bomb plot people could lose life '' . add : `` police say take seriously '' ... acknowledge `` good libertarian argument '' card , say shadow cabinet weigh `` conflict interest '' reach decision . `` n't pretend easy decision end day decision take . '' also deny afraid look `` soft '' issue , compare labour . conservative announce support government plan monday even ... source within party tell bbc mr howard always favour id card , try introduce home secretary . tory insist would hold minister account precise purpose scheme ... say would also press labour whether objective could meet whether home office would able deliver . pledge assess cost effectiveness id card whether people 's privacy would properly protect . `` important remember bill take decade come full effect , '' spokesman say . lib dem home affair spokesman mark oaten brand id scheme waste money `` deeply flaw '' . say : `` sign michael howard overrule colleague ' concern id card . `` .. chairman bar council , guy mansfield qc warn real risk people `` margin society '' would drive hand extremist . `` go happen young asian men bomb go somewhere ? go stop . n't [ id card ] go detain . '' tory ex-minister douglas hogg say oppose plan id card brand `` regressive '' step would intrude life ordinary citizen without counterbalance benefit . predict ultimately carry card would become compulsory would lead large number britain 's ethnic minority stop police ."},
 {'TextID': 3,
  'Text': "observer monitor uk election .. minister invite international observer check forthcoming uk general election fairly run ... move come amid claim poll could mar electoral fraud . report two mp committee call thursday urgent change electoral registration system combat vote rig boost turnout . write response labour mp gordon prentice , government say would normally invite observer uk election ... junior constitutional affair minister christopher leslie say : `` fully expect u repeat previous practice date next general election announce . '' government look way boost voter turnout , fell 59 % last general election 2001 ... trial all-postal ballot four english region last summer hit delay fraud allegation . liberal democrat peer lord greave call last week international observer general election - say otherwise could month court challenge `` scale see since 19th century '' . thursday 's report draw two committee scrutinise work office deputy prime minister ( odpm ) department constitutional affair ( dca ) . say , growth postal vote , strong case tighten fraud protection require voter register individually , rather household . also say three million people eligible vote register ... figure 2001 general election suggest 29 % people age 18 24 , 19 % black voter electoral roll . young people share accommodation think miss one act head household fill form . odpm committee chairman andrew bennett say individual voter registration , oppose registration household , quickly introduce could `` dramatically reduce chance fraud '' . counterpart dca committee , alan beith , say delay `` measure likely increase registration put place prove effective . '' shadow constitutional affair secretary oliver heald accuse government `` drag foot '' `` badly need measure '' . `` vital move ahead northern ireland system individual electoral registration safeguard integrity britain 's electoral system , '' say ... report say individual registration treat carefully 12 % voter disappear electoral roll northern ireland introduce 2002. report say government consider fine unregistered voter , accept many expert say would expensive system would hard enforce . say incentive register , £20 council tax rebate , likely see `` gimmick '' risk undermine integrity system , mp say . instead call `` imaginative campaign '' boost interest ."},
 {'TextID': 4,
  'Text': "kilroy name election seat target .. ex-chat show host robert kilroy-silk contest derbyshire seat erewash next general election ... labour 's elizabeth blackman seat 1997 6,932 majority . say fight record `` hard-working constituency mp '' . mr kilroy-silk announce plan day launch new party , veritas , latin truth . east midland mep , quit uk independence party , want new group `` change face '' uk politics . choice election constituency quash speculation would stand defence secretary geoff hoon ashfield , nottinghamshire . ukip 31 % vote erewash last june 's european election - mr kilroy-silk among candidate region . 1997 , erewash hold tory since 1970. m blackman say proud government 's achievement area . decline give view mr kilroy-silk point ... thursday , tell london news conference veritas would avoid old party ' `` lie spin '' . say `` country '' `` steal u '' mass immigration promise `` firm fair '' policy immigration . veritas say hope contest seat forthcoming general election plan announce detail policy crime , tax , pension , health defence next week ... ukip leader roger knapman say glad see back mr kilroy-silk . labour campaign spokesman fraser kemp say veritas join `` already crowd field right british politics '' . mr kilroy-silk join new venture one ukip 's two london assembly member , damien hockney , veritas ' deputy leader ... ukip 's chairman petrina holdsworth say group parody party men leave . mr kilroy-silk quit ukip last week month tension vie unsuccessfully leadership party . say ashamed member ukip whose leadership `` go awol '' great opportunity offer third place last june 's european election . ukip 's leader , roger knapman , say glad see back mr kilroy-silk . `` remarkable ability influence people , sadly , [ european ] election become clear interest robert kilroy-silk party uk independence party nice know , 'goodbye ' , '' say . ukip official also argue mr kilroy-silk `` straightforward '' attack party want lead ."},
 {'TextID': 5,
  'Text': "donor attack blair-brown 'feud ' .. report feud tony blair gordon brown prompt labour donor say almost certainly refuse give fund ... duncan bannatyne also attack government iraq `` poor '' response asian tsunami crisis . broadside come ex-foreign secretary robin cook say hop mr brown would premier point . mr bannatyne previously give labour £50,000 . make fortune care home health club ... 52-year-old tuesday say review donation cabinet disunity international issue . spokesman say highly unlikely would give labour money , although would remain supporter fund conservative ... robert peston 's new book prompt speculation blair-brown rift claim prime minister break promise make 2003 stand . mr bannatyne say : `` disunity cabinet corrosive effect country . `` gordon brown great chancellor deliver stable economy , business want continue blow course petty squabble base personal ambition . '' businessman , whose late venture casino newcastle , also voice concern ongoing violence iraq ... brand uk government 's response tsunami `` piecemeal poor '' . `` people need practical help pledge money , '' say . `` u force help grind - . '' british navy ship help relief effort prime minister say government could ultimately give hundred million pound aid . mr bannatyne due host new television programme also appear bbc2 business start-up programme dragon 's den . spokesman insist attack labour publicity stunt ... separate development , robin cook give support mr brown 's prime ministerial ambition tell lunch political journalist win election labour 's election . insist recent squabble mr blair mr brown `` perceive problem voter , '' add impression governmental incompetence . mr cook argue prominence give matter `` alternative source opposition government '' . warn `` abstention party '' real challenge labour - would motivate mr blair 's promise produce `` unremittingly new labour '' election manifesto . comment come dave prentis , leader britain 's big union unison , tell daily record newspaper want date set mr blair replace labour leader ."},
 {'TextID': 6,
  'Text': "research fear kelly 's view .. scientist express concern new education secretary ruth kelly 's religious view could hamper vital scientific research ... m kelly , catholic , report `` pro-life '' oppose embryo research . medical research council professor nancy rothwell say m kelly 's view matter responsible train future scientist . department education skill would comment concern ... spokeswoman say : `` news m kelly catholic go detail . '' add claim m kelly charge £1bn university research budget true . high education fund council research council decide university ' research allocation . british law open clone human embryo create stem cell , master cell develop body 's tissue type . clone activity permit reproductive purpose - research new disease treatment . however , controversial involve destruction embryo ... professor rothwell , also vice-president research manchester university , tell time high education supplement would worry `` great deal '' minister anti-stem cell . say : `` view minister dfes matter responsible train next generation scientist . `` ca n't high education policy odds government 's science policy . '' head developmental genetics national institute medical research , professor robin lovell-badge , say witness confuse situation u many religious group oppose practice . say : `` someone senior ruth kelly go favour stem cell research end similarly schizophrenic system country . worry . '' fertility expert lord winston say think `` rather good '' minister hold ethical view . concern also raise `` pro-choice '' organisation m kelly 's view might affect sex education policy school ... family plan association chief executive , anne weyman , say teach pupil contraception abortion key . `` young people must inform issue within sexual health , include contraception abortion . `` think important government maintain commitment teenage pregnancy strategy . '' currently , individual school devise sex education policy base framework provide dfes . m kelly set detail view either issue yet , say intend put parent first education policy . would include quality teach , classroom discipline academic standard school , say ."},
 {'TextID': 7,
  'Text': "chancellor rally labour voter .. gordon brown issue rally cry , tell supporter `` stake high '' stay home protest vote forthcoming general election ... chancellor say vote - expect fall 5 may - give `` clear fundamental '' choice labour investment conservative cut . speak labour 's spring conference gateshead , mr brown claim nh safe conservative hand . say tory plan cut £35bn tax would `` cut deep public service '' ... pack audience gateshead 's sage centre , chancellor say cut propose shadow chancellor oliver letwin equivalent sack every teacher , gp nurse country , tell activist . lay conservative 's record government say : `` give promise - labour , britain never return mistake erm 10 % inflation , 15 % interest rate , £3bn lose reserve , 250,000 repossess , one million negative equity three million unemployed . `` never tory boom bust ... '' central divide line election , conservative party take britain back plan deep cut £35bn service , labour government take britain forward , platform stability reform renew hospital , school public service , proud say , spend 2008 £60bn . '' turn economy , chancellor pledge continue economic stability growth third term power ... say seven year labour transform party trust economy `` party trust economy '' . `` party employee , employer manager '' , say . speech - prompt stand ovation audience clearly `` warm '' mr brown - also promise end teenage unemployment within next five year . also highlight plan 100 % debt relief world 's poor country , national minimum wage 16 17-year-olds creation network child 's centre flexibility maternity leave . prime minister take part late saturday interactive question answer session , field query send e-mail , text message telephone part labour 's attempt engage public campaign ."},
 {'TextID': 8,
  'Text': "fox attack blair 's tory 'lies ' .. tony blair lie take uk war qualm lie election campaign , say tory ... tory co-chairman liam fox speak mr blair tell labour member tory offer `` hard right agenda '' . dr fox tell bbc radio : `` will lie reason go war , guess go lie anything . '' would discus report party repay £500,000 lord ashcroft predict election defeat ... prime minister ratchet labour 's pre-election campaign weekend helicopter tour country speech party 's spring conference . insist know poll date , widely expect 5 may ... see highly personal speech gateshead sunday , mr blair say : `` passion hunger first walk door 10 down street . '' describe relationship public start euphoric , struggle live expectation , reach point raise voice `` throw crockery '' . warn supporter complacency , say : `` 's fight future country , 's fight britain people britain win . `` .. mr blair say whether public choose michael howard mr kennedy , would result `` tory government labour government country go back move forward '' . dr fox accuse mr blair cabinet minister tell lie opponent ' policy attack lie . `` learn weekend labour tactic go 's go fear smear , '' tell bbc news . tory co-chairman attack labour 's six new pledge `` vacuous '' say mr blair worry voter would take revenge failure deliver . dr fox refuse discus weekend newspaper report party repay £500,000 former tory treasurer lord ashcroft say party could win election . `` repay loan due comment individual financial matter , '' say , insist enjoy `` warm constructive '' relationship lord ashcroft ... meanwhile lib dem leader charles kennedy expect attack mr blair 's word begin nationwide tour monday . mr kennedy accelerate lib dem election preparation week visit manchester , liverpool , leicester , somerset , basingstoke , shrewsbury , dorset torbay . say : `` three-party politics . northern city , contest labour liberal democrat . `` southern rural seat - especially south west - principal contender liberal democrat conservative , run scotland wale . '' lib dems accuse mr blair make `` touchy-feely '' speech labour delegate help regain public trust ."},
 {'TextID': 9,